---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.api.name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-pod-reader
rules:
  - verbs:
      - get
      - list
    apiGroups: [""]
    resources:
      - endpoints
      - pods
      - services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.services.api.name}}-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.api.name }}
  labels:
    app: {{ .Values.services.api.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.api.name }}
    spec:
      serviceAccountName: {{.Values.services.api.name}}-sa
      containers:
        - name: {{ .Values.services.api.name }}
          image: {{ .Values.services.api.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.api.port }}
          env:
            - name: HOST_POS
              value: {{ .Values.services.pos.name }}
            - name: HOST_DATA
              value: {{ .Values.services.data.name }}
            - name: HAZEL_CLUSTER_NAME
              value: {{ .Values.services.api.hazelcast.cluster }}
            - name: HAZEL_K8S_SERVICE_ENABLED
              value: {{ .Values.services.api.hazelcast.k8s }}
            - name: HAZEL_TCPIP_SERVICE_ENABLED
              value: {{ .Values.services.api.hazelcast.tcp }}
            - name: HAZEL_K8S_SERVICE_NAME
              value: {{ .Values.services.api.hazelcast.service }}
            - name: HAZEL_K8S_NAMESPACE
              value: {{ .Values.services.api.hazelcast.namespace }}
            - name: HAZEL_K8S_PORT
              value: {{ .Values.services.api.hazelcast.port }}
            - name: HAZEL_METRICS
              value: {{ .Values.services.api.hazelcast.metrics }}
            - name: HAZELCAST_LOGGING_TYPE
              value: {{ .Values.services.api.hazelcast.logging }}
        {{- if .Values.services.api.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.services.api.healthCheck.path }}
              port: {{ .Values.services.api.port }}
            initialDelaySeconds: {{ .Values.services.api.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.api.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.services.api.healthCheck.path }}
              port: {{ .Values.services.api.port }}
            initialDelaySeconds: {{ .Values.services.api.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.api.healthCheck.periodSeconds }}
        {{- end }}
          resources:
          {{- toYaml .Values.services.api.resources | nindent 12 }}