{{- if .Values.services.data.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.data.name }}
  minReplicas: {{ .Values.services.data.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.data.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.data.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.data.hpa.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- if .Values.services.cache.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.cache.name }}
  minReplicas: {{ .Values.services.cache.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.cache.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.cache.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.cache.hpa.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- if .Values.services.pos.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.pos.name }}
  minReplicas: {{ .Values.services.pos.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.pos.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.pos.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.pos.hpa.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- if .Values.services.api.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.api.name }}
  minReplicas: {{ .Values.services.api.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.api.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.api.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.api.hpa.targetMemoryUtilizationPercentage }}
{{- end }}