---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.data.name }}
spec:
  selector:
    app: {{ .Values.services.data.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.data.port }}
      targetPort: {{ .Values.services.data.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.cache.name }}
spec:
  selector:
    app: {{ .Values.services.cache.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.cache.port }}
      targetPort: {{ .Values.services.cache.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.pos.name }}
spec:
  selector:
    app: {{ .Values.services.pos.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.pos.port }}
      targetPort: {{ .Values.services.pos.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.api.name }}
spec:
  selector:
    app: {{ .Values.services.api.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.api.externalPort }}
      targetPort: {{ .Values.services.api.port }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  type: ClusterIP
---