management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
        readiness:
          include:
            - readinessState
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
server:
  port: 8087
  servlet:
    context-path: /ms-api

api:
  config:
    rest:
      pos:
        url: http://${HOST_POS}:8090/ms-pos
        debug: true
      data:
        url: http://${HOST_DATA}:8089/ms-data
        debug: true
spring:
  webflux:
    base-path: /ms-api
logging:
  level:
    com.empresa: DEBUG